{"name": "case login from api with invalid email", "status": "passed", "steps": [{"name": "Login to {'email': 'wrong-email', 'password': '123456'} from api", "status": "passed", "start": 1663741923644, "stop": 1663741923644}], "attachments": [{"name": "log", "source": "1f4beee7-67ea-4bd3-a9ad-2f9e2d653f1e-attachment.txt", "type": "text/plain"}], "start": 1663741923638, "stop": 1663741923644, "uuid": "19328418-aee2-4f84-97f8-9beefd6ebace", "historyId": "71a6cfc8ac786e68bc87c3db7cf40107", "testCaseId": "7c1c9c1379edd232fe92ebc02cc700be", "fullName": "test_authentication_system.TestAuthenticationAPI#test_login_invalid_email", "labels": [{"name": "feature", "value": "Feature: Login"}, {"name": "epic", "value": "API Authentication system"}, {"name": "tag", "value": "@pytest.mark.usefixtures('safe_load')"}, {"name": "suite", "value": "test_authentication_system"}, {"name": "subSuite", "value": "TestAuthenticationAPI"}, {"name": "host", "value": "DESKTOP-6448GON"}, {"name": "thread", "value": "32204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_authentication_system"}]}