{"name": "case login from api with invalid email", "status": "passed", "steps": [{"name": "Login to {'email': 'wrong-email', 'password': '123456'} from api", "status": "passed", "start": 1663743284601, "stop": 1663743284601}], "attachments": [{"name": "log", "source": "17fb09a9-af43-4c0d-9603-b323674d73a0-attachment.txt", "type": "text/plain"}], "start": 1663743284546, "stop": 1663743284602, "uuid": "08864047-fae5-4346-b89f-8e8bef98fae3", "historyId": "71a6cfc8ac786e68bc87c3db7cf40107", "testCaseId": "7c1c9c1379edd232fe92ebc02cc700be", "fullName": "test_authentication_system.TestAuthenticationAPI#test_login_invalid_email", "labels": [{"name": "epic", "value": "API Authentication system"}, {"name": "feature", "value": "Feature: Login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('safe_load')"}, {"name": "suite", "value": "test_authentication_system"}, {"name": "subSuite", "value": "TestAuthenticationAPI"}, {"name": "host", "value": "DESKTOP-6448GON"}, {"name": "thread", "value": "38916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_authentication_system"}]}